-- URLS create if not exists
CREATE TABLE IF NOT EXISTS urls (
  id   INTEGER PRIMARY KEY,
  url  TEXT NOT NULL,
  code TEXT NOT NULL,
  md5  TEXT NOT NULL UNIQUE,
  hits INTEGER DEFAULT 0,
  last_used DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
